# Generated by Django 5.1.6 on 2025-02-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_assignment_assigned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquisition',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
