# Generated by Django 5.1.6 on 2025-02-20 21:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_acquisition_removed_at_assignment_removed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 20, 21, 36, 11, 851675, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
